[package]
name = "mpm-rs"
version = "0.1.0"
authors = ["Ziyang Li <liby99@seas.upenn.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
specs = "0.15"
nalgebra = "0.18"
rand = "0.7.2"
pbr = "1.0"